database:
  schema:
    signal: sigcontrol_copy_330200
logging:
  level:
    com:
      ct:
        '*': debug
server:
  port: 8081
spring:
  profiles:
    include:
      - global
      - jdbc
  redis:
    host: ${redis.ip}
    password:
    port: ${redis.port}
    timeout: 5000
    jedis:
      pool:
        max-idle: 20
        max-wait: 3000
        max-active: 100
        min-idle: 0
